package com.fieldtripops.domain.model

import java.time.Instant

enum class SlaReminderKind {
    FIRST_RESPONSE_PRE_BREACH,
    RESOLUTION_PRE_BREACH,
    FIRST_RESPONSE_BREACHED,
    RESOLUTION_BREACHED
}

/**
 * On-device reminder row generated by SLA evaluation before a breach of the
 * first-response or resolution SLA. Purely local — no remote notification path.
 */
data class SlaReminder(
    val id: String,
    val ticketId: String,
    val kind: SlaReminderKind,
    val dueAt: Instant,
    val generatedAt: Instant,
    val slaConfigVersion: Long,
    val acknowledged: Boolean,
    val message: String
)
